// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CB_Gift.Models;

public partial class DesignerSeller
{
    public string DesignerUserId { get; set; }

    public string SellerUserId { get; set; }

    public DateTime CreatedAt { get; set; }

    public string CreatedByUserId { get; set; }
}