// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CB_Gift.Models;

public partial class EndCustomer
{
    public int CustId { get; set; }

    public string Name { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string Address { get; set; }

    public string Address1 { get; set; }

    public string Zipcode { get; set; }

    public string ShipState { get; set; }

    public string ShipCity { get; set; }

    public string ShipCountry { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}