// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CB_Gift.Models;

public partial class OrderStatus
{
    public int StatusId { get; set; }

    public string Code { get; set; }

    public string NameVi { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}