// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using CB_Gift.Data;
using System;
using System.Collections.Generic;

namespace CB_Gift.Models;

public partial class Order
{
    public int OrderId { get; set; }

    public string OrderCode { get; set; }

    public DateTime OrderDate { get; set; }

    public int EndCustomerId { get; set; }

    public string SellerUserId { get; set; }
    public virtual AppUser SellerUser { get; set; }

    public DateTime? CreationDate { get; set; }

    public decimal? CostScan { get; set; }

    public bool? ActiveTts { get; set; }

    public decimal? TotalCost { get; set; }

    public string ProductionStatus { get; set; }

    public string PaymentStatus { get; set; }

    public string Tracking { get; set; }

    public int StatusOrder { get; set; }

    public int? ToProvinceId { get; set; }

    public int? ToDistrictId { get; set; }
    public string? ToWardCode { get; set; }

    public virtual EndCustomer EndCustomer { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual OrderStatus StatusOrderNavigation { get; set; }
}