// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CB_Gift.Models;

public partial class OrderDetailDesign
{
    public int DesignId { get; set; }

    public int OrderDetailId { get; set; }

    public string DesignerUserId { get; set; }

    public string FileUrl { get; set; }

    public string Note { get; set; }

    public bool IsFinal { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual OrderDetail OrderDetail { get; set; }
}