// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CB_Gift.Models;

public partial class OrderDetail
{
    public int OrderDetailId { get; set; }

    public int OrderId { get; set; }

    public int ProductVariantId { get; set; }

    public string LinkImg { get; set; }

    public string LinkThanksCard { get; set; }

    public string LinkFileDesign { get; set; }

    public string Accessory { get; set; }

    public string Note { get; set; }

    public DateTime? CreatedDate { get; set; }

    public int Quantity { get; set; }

    public bool NeedDesign { get; set; }

    public string AssignedDesignerUserId { get; set; }

    public DateTime? AssignedAt { get; set; }

    public virtual Order Order { get; set; }

    public virtual OrderDetailDesign OrderDetailDesign { get; set; }

    public virtual ICollection<PlanDetail> PlanDetails { get; set; } = new List<PlanDetail>();

    public virtual ProductVariant ProductVariant { get; set; }
}