// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CB_Gift.Models;

public partial class PlanDetail
{
    public int PlanDetailId { get; set; }

    public int PlanId { get; set; }

    public int OrderDetailId { get; set; }

    public int? StatusOrder { get; set; }

    public int? NumberOfFinishedProducts { get; set; }

    public virtual OrderDetail OrderDetail { get; set; }

    public virtual Plan Plan { get; set; }

    public virtual ICollection<Qc> Qcs { get; set; } = new List<Qc>();
}