// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CB_Gift.Models;

public partial class Plan
{
    public int PlanId { get; set; }

    public DateTime? CreateDate { get; set; }

    public string CreateByUserId { get; set; }

    public string ApproveByUserId { get; set; }

    public DateTime? ApproveDate { get; set; }

    public DateTime? StartDatePlan { get; set; }

    public DateTime? StopDatePlan { get; set; }

    public virtual ICollection<PlanDetail> PlanDetails { get; set; } = new List<PlanDetail>();
}