// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CB_Gift.Models;

public partial class ProductVariant
{
    public int ProductVariantId { get; set; }

    public int ProductId { get; set; }

    public decimal? LengthCm { get; set; }

    public decimal? HeightCm { get; set; }

    public decimal? WidthCm { get; set; }

    public decimal? WeightGram { get; set; }

    public decimal? ShipCost { get; set; }

    public decimal? BaseCost { get; set; }

    public string ThicknessMm { get; set; }

    public string SizeInch { get; set; }

    public string Layer { get; set; }

    public string CustomShape { get; set; }

    public string Sku { get; set; }

    public decimal? ExtraShipping { get; set; }

    public decimal? TotalCost { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual Product Product { get; set; }
}