// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CB_Gift.Models;

public partial class Product
{
    public int ProductId { get; set; }

    public int CategoryId { get; set; }

    public string ProductName { get; set; }

    public string ProductCode { get; set; }

    public int? Status { get; set; }

    public string ItemLink { get; set; }

    public string Describe { get; set; }

    public string Template { get; set; }

    public virtual Category Category { get; set; }

    public virtual ICollection<ProductVariant> ProductVariants { get; set; } = new List<ProductVariant>();

    public virtual ICollection<Tag> Tags { get; set; } = new List<Tag>();
}