// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CB_Gift.Models;

public partial class Qc
{
    public int QccheckId { get; set; }

    public int PlanDetailId { get; set; }

    public string CheckedByUserId { get; set; }

    public DateTime? CheckedDate { get; set; }

    public int? QuantityChecked { get; set; }

    public int? QuantityPassed { get; set; }

    public int? QuantityFailed { get; set; }

    public string Remark { get; set; }

    public virtual PlanDetail PlanDetail { get; set; }
}