// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CB_Gift.Models;

public partial class Tag
{
    public int TagsId { get; set; }

    public string TagName { get; set; }

    public string TagCode { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}