# Tên của App trên DigitalOcean
name: cb-gift-app

# Danh sách các component (container)
services:
# --- Component 1: Backend API ---
- name: api
  # Lấy code từ gốc
  github:
    repo: dyann2003/CB-Gift
    branch: main # <-- ĐỔI TÊN BRANCH NẾU CẦN (ví dụ: Fix_DockerFile)
    
  # Cấu hình build cho backend
  dockerfile_path: Dockerfile # <-- Trỏ tới file backend
  
  # Cấu hình mạng cho backend
  http_port: 8080
  routes:
  - path: /api # <-- Mọi request tới /api sẽ vào đây
  
  # Cấu hình gói $12/mo (Bạn có thể đổi "basic-xs")
  instance_size_slug: basic-xs 
  instance_count: 1
  
  # --- Biến môi trường cho Backend API ---
  envs:
  - key: ConnectionStrings__DefaultConnection
    value: "Server=db-mysql-sgp1-17178-do-user-27268406-0.h.db.ondigitalocean.com;Port=25060;Database=defaultdb;Uid=doadmin;Pwd=AVNS_4Km1VH9_UvXaePAXjIU;SslMode=Required"
    type: SECRET
  - key: Jwt__Issuer
    value: "CBGift.Auth"
  - key: Jwt__Audience
    value: "CBGift.Client"
  - key: Jwt__Key
    value: "CHANGE_ME_TO_A_32_CHAR_MIN_SECRET__2025!!"
    type: SECRET
  - key: Seed__Email
    value: "demo@cbgift.local"
  - key: Seed__Password
    value: "Demo@123!"
    type: SECRET
  - key: Email__Sender
    value: "quanghuytn2022@gmail.com"
  - key: Email__Password
    value: "upsm aocs ltro reza"
    type: SECRET
  - key: App__ClientUrl
    value: ${client.URL} # <-- Tự động lấy URL của client
  - key: CloudinarySettings__CloudName
    value: "ddutk6rhm"
  - key: CloudinarySettings__ApiKey
    value: "925764161782478"
  - key: CloudinarySettings__ApiSecret
    value: "T1OlrM_QFoOP5frzKncwEoyQNRo"
    type: SECRET
  - key: PayOS__ClientId
    value: "922abe15-a1cc-446e-98d9-4452f9958748"
  - key: PayOS__ApiKey
    value: "85b05501-0365-4b65-8dc9-e17d7d89b1c2"
    type: SECRET
  - key: PayOS__ChecksumKey
    value: "81d14b5735c3211744bec62923ebaa03e7bc22ebe423dcb644a4f13baa9b935a"
    type: SECRET
  - key: GeminiSettings__ApiKey
    value: "AIzaSyD5dnu-G_YxpyN8ANVu4qYdnrirxu8BHA0"
    type: SECRET
  - key: StabilityAiSettings__ApiKey
    value: "sk-9JH5wIDlWnF3LPO55SWGKPVQv6Q01dGq0qYdvIe7Z7RVvHiC"
    type: SECRET


# --- Component 2: Frontend Client ---
- name: client
  # Lấy code từ gốc
  github:
    repo: dyann2003/CB-Gift
    branch: main # <-- ĐỔI TÊN BRANCH NẾU CẦN
  
  # Cấu hình build cho frontend
  dockerfile_path: Dockerfile.frontend # <-- Trỏ tới file frontend
  
  # Cấu hình mạng cho frontend
  http_port: 80 # <-- Cổng 80 của Nginx
  routes:
  - path: / # <-- Đặt làm trang chủ
  
  # Cấu hình gói $12/mo
  instance_size_slug: basic-xs
  instance_count: 1
  
  # --- Biến môi trường cho Frontend Client ---
  envs:
  - key: NEXT_PUBLIC_API_URL
    value: ${api.URL} # <-- Tự động lấy URL của backend